# Generated by Django 5.1.6 on 2025-03-30 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hello', to=settings.AUTH_USER_MODEL),
        ),
    ]
