# Generated by Django 5.1.6 on 2025-03-30 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_barberprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='image',
            field=models.ImageField(default='default-barber.png', upload_to='barbers/'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_barber', to=settings.AUTH_USER_MODEL),
        ),
    ]
