# Generated by Django 5.1.6 on 2025-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_barberprofile_image_alter_barberprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='image',
            field=models.ImageField(blank=True, default='default-barber.png', null=True, upload_to='barbers/'),
        ),
    ]
